# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: mcr.microsoft.com/playwright:bionic

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - run: docker pull mcr.microsoft.com/playwright:bionic
      - run: docker run -it --rm --ipc=host mcr.microsoft.com/playwright:bionic /bin/bash
          
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      

      #- save_cache:
          #paths:
            #- node_modules
          #key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: pwd
      - run: ls
      - run: node playwright.js
